INSERT INTO aliada.rdfizer_job_
	instances (job_id, datafile, format, namespace, graph_name, aliada_ontology, start_date, end_date, sparql_endpoint_uri, sparql_endpoint_login, sparql_endpoint_password)
	VALUES(
	'1', '/work/data/aliada/unimarc.xml', 'unimarcxml', 'http://rdf.atcult.it/', 'http://rdf.atcult.it', 
	'http://aliada-project.eu/2014/aliada-ontology/#', null, null, 
	'http://rdfstore:8080/openrdf-workbench', null, null)

INSERT INTO aliada.linksdiscovery_job_instances (input_uri, input_login, input_password, input_graph, output_uri, output_login, output_password, output_graph, tmp_dir, client_app_bin_dir,client_app_user) VALUES (1, 'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib', 'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp', '/home/aliada/links-discovery/bin/', 'linking', default, default);
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,1,'ALIADA_DBPedia', '/work/data/aliada/links-discovery/config/silk/aliada_dbpedia_config.xml',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,2,'ALIADA_GeoNames', '/work/data/aliada/links-discovery/config/silk/aliada_geonames_config.xml',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,3,'ALIADA_Freebase', '/work/data/aliada/links-discovery/config/silk/aliada_freebase_config.xml',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,4,'ALIADA_BNE', '/work/data/aliada/links-discovery/config/silk/aliada_bne_config.xml',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,5,'ALIADA_BNB', '/work/data/aliada/links-discovery/config/silk/aliada_bnb_config.xml',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,6,'ALIADA_Europeana', '/work/data/aliada/links-discovery/config/silk/aliada_europeana_config.xml',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,7,'ALIADA_NSZL', '/work/data/aliada/links-discovery/config/silk/aliada_nszl_config.xml',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,8,'ALIADA_MARC', '/work/data/aliada/links-discovery/config/silk/aliada_marc_config.xml',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,9,'ALIADA_VIAF', '',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,10,'ALIADA_Lobid: Libraries & rel. orgs', '',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,11,'ALIADA_Lobid: Bibliographic Resources', '',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,12,'ALIADA_Library of Congress SH', '',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');
INSERT INTO aliada.linksdiscovery_subjob_instances (job_id, subjob_id, name, config_file, num_threads, reload_source, reload_target, output_uri, output_login, output_password, output_graph, tmp_dir) VALUES (1,13,'ALIADA_Open Library', '',8,1,0,'http://aliada.scanbit.net:8891/sparql-auth', 'aliada_dev', 'aliada_dev', 'http://data.artium.org/id/collections/library/bib/links', '/home/aliada/tmp');